# Generated by Django 3.1.7 on 2021-03-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20210310_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['timestamp']},
        ),
    ]
