# Generated by Django 3.1.7 on 2021-03-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_frontend', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
